blank_issues_enabled: false
contact_links:
  - name: Customcord Support Server
    url: https://discord.gg/D9uwnFnqmd
    about: If you need help regarding CustomCord, please join our support server!
  - name: CustomCord Installer
    url: https://github.com/Vencord/Installer
    about: You can find the Customcord Installer here
